/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ryuk.gui;

import com.ryuk.partidas.PartidaDamas;
import static com.ryuk.util.Constantes.ICON_UI_IMAGE;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edyrr
 */
public class UICargarPartidaDamas extends javax.swing.JFrame {

    private ArrayList<PartidaDamas> listDamas;
    private UIPartidaManageDamas windowBack;
    private UIMenu windowMain;

    /**
     * Creates new form UICargarPartidaBy
     */
    public UICargarPartidaDamas(ArrayList<PartidaDamas> _listDamas, UIPartidaManageDamas _windowBack, UIMenu _windowMain) {
        initComponents();
        this.listDamas = _listDamas;
        ImageIcon icon = new ImageIcon(ICON_UI_IMAGE);
        this.setIconImage(icon.getImage());
        this.setVisible(true);
        this.windowMain = _windowMain;
        this.windowBack = _windowBack;
        txtIdPartida.requestFocus();
        txtIdPartida.selectAll();
        cargarPartidas();
    }

    public void cargarPartidas() {

        if (listDamas.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay partidas guardadas :C",
                    "Vacia", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tablePartidas.getModel();
        for (PartidaDamas partida : listDamas) {
            model.addRow(new Object[]{partida.getID(), partida.getJugadorUno().getNombre(),
                partida.getJugadorDos().getNombre(), partida.timeToString()});
        }

        tablePartidas.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePartidas = new javax.swing.JTable();
        lblPartidaID = new javax.swing.JLabel();
        txtIdPartida = new javax.swing.JTextField();
        btnCargarPartida = new javax.swing.JButton();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(0, 0, 0));

        tablePartidas.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        tablePartidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jugador Uno", "Jugador Dos", "Tiempo Transcrurrido", "Estado de Partida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePartidas.setEnabled(false);
        jScrollPane1.setViewportView(tablePartidas);
        if (tablePartidas.getColumnModel().getColumnCount() > 0) {
            tablePartidas.getColumnModel().getColumn(0).setPreferredWidth(15);
        }

        lblPartidaID.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblPartidaID.setForeground(new java.awt.Color(255, 255, 255));
        lblPartidaID.setText("ID de partida a cargar");

        txtIdPartida.setText("Ingrese ID");

        btnCargarPartida.setBackground(new java.awt.Color(7, 7, 60));
        btnCargarPartida.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnCargarPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnCargarPartida.setText("Cargar Partida");
        btnCargarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarPartidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPartidaID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdPartida))
                .addGap(29, 29, 29)
                .addComponent(btnCargarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                        .addComponent(lblPartidaID)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnCargarPartida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        bgPanel.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 830, 440));

        lblBackGround.setIcon(new javax.swing.ImageIcon("D:\\proyectos_u\\proyecto2\\resource\\BackGroundR3.jpg")); // NOI18N
        bgPanel.add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        windowBack.setFocusMe();
    }//GEN-LAST:event_formWindowClosing

    private void btnCargarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarPartidaActionPerformed
        // TODO add your handling code here:
        try {
            if (listDamas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No existen partidas guardadas");
                return;
            }
            int selectId = Integer.parseInt(txtIdPartida.getText());
            PartidaDamas tmpPt = null;
            
            try {
                 tmpPt = (PartidaDamas) cargarPartida(selectId).clone();
            } catch (CloneNotSupportedException e) {
                JOptionPane.showMessageDialog(this, "Error clonando objeto Partida Damas");
            }

            if (tmpPt == null) {
                JOptionPane.showMessageDialog(this, "No se selecciono ninguna partida");
                return;
            }

            new UIDamasChinas(tmpPt, listDamas, windowMain, true);
            this.dispose();
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Solo se admite el ingreso numeros!!",
                    "Advertencia", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnCargarPartidaActionPerformed

    public PartidaDamas cargarPartida(int ID) {
        for (PartidaDamas partida : listDamas) {
            if (partida.getID() == ID) {
                return partida;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton btnCargarPartida;
    private javax.swing.JPanel content;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblPartidaID;
    private javax.swing.JTable tablePartidas;
    private javax.swing.JTextField txtIdPartida;
    // End of variables declaration//GEN-END:variables
}
