/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ryuk.gui;

import com.ryuk.partidas.PartidaDamas;
import com.ryuk.partidas.PartidaHanoi;
import com.ryuk.player.Player;
import static com.ryuk.util.Constantes.ICON_UI_IMAGE;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author edyrr
 */
public class UIReportes extends javax.swing.JFrame {

    private ArrayList<PartidaDamas> listaDamas;
    private ArrayList<PartidaHanoi> listaHanoi;
    private ArrayList<Player> listaJugadores;
    private UIMenu windowMain;

    /**
     * Creates new form UIReportes
     */
    public UIReportes(ArrayList _listaDamas, ArrayList _listaHanoi, ArrayList _listaJugadores, UIMenu _windowMain) {
        initComponents();
        this.listaDamas = _listaDamas;
        this.listaHanoi = _listaHanoi;
        this.listaJugadores = _listaJugadores;
        this.windowMain = _windowMain;
        ImageIcon icon = new ImageIcon(ICON_UI_IMAGE);
        this.setIconImage(icon.getImage());
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnReportesDamas = new javax.swing.JButton();
        btnReporteHanoi = new javax.swing.JButton();
        lblTitleReportes = new javax.swing.JLabel();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReportesDamas.setBackground(new java.awt.Color(7, 7, 60));
        btnReportesDamas.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnReportesDamas.setForeground(new java.awt.Color(255, 255, 255));
        btnReportesDamas.setText("Reportes Damas");
        btnReportesDamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesDamasActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportesDamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 250, 75));

        btnReporteHanoi.setBackground(new java.awt.Color(7, 7, 60));
        btnReporteHanoi.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnReporteHanoi.setForeground(new java.awt.Color(255, 255, 255));
        btnReporteHanoi.setText("Reportes Torres de Hanoi");
        btnReporteHanoi.setToolTipText("");
        btnReporteHanoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteHanoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporteHanoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 250, 75));

        lblTitleReportes.setFont(new java.awt.Font("Lato", 1, 48)); // NOI18N
        lblTitleReportes.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleReportes.setText("Reportes");
        jPanel1.add(lblTitleReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        lblBackGround.setIcon(new javax.swing.ImageIcon("D:\\proyectos_u\\proyecto2\\resource\\BackGroundR3.jpg")); // NOI18N
        jPanel1.add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 770, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesDamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesDamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportesDamasActionPerformed

    private void btnReporteHanoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteHanoiActionPerformed
        // TODO add your handling code here:
        new UIReportesHanoi(listaHanoi, listaJugadores, windowMain);
        this.dispose();
    }//GEN-LAST:event_btnReporteHanoiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        windowMain.setFocusMain();
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReporteHanoi;
    private javax.swing.JButton btnReportesDamas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblTitleReportes;
    // End of variables declaration//GEN-END:variables
}
