/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ryuk.gui;

import com.ryuk.util.Constantes;
import static com.ryuk.util.Constantes.ICON_UI_IMAGE;
import com.ryuk.util.Utils;
import com.ryuk.player.Player;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edyrr
 */
public class UIUserManage extends javax.swing.JFrame implements Constantes{

    private final ArrayList<Player> listaJugadores;
    private UIMenu windowMain;
    private int indexUpdate;

    /**
     * Creates new form UIUserManage
     */
    public UIUserManage(ArrayList<Player> _listaJugadores, UIMenu _windowMain) {
        initComponents();
        this.listaJugadores = _listaJugadores;
        this.windowMain = _windowMain;
        this.setVisible(true);
        ImageIcon icon = new ImageIcon(ICON_UI_IMAGE);
        this.setIconImage(icon.getImage());
        txtNombre.requestFocus();
        txtNombre.selectAll();
        btnCrearJugador.setMnemonic(KeyEvent.VK_ENTER);
        btnEditar.setMnemonic(KeyEvent.VK_ENTER);
        cargarListaJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        btnCrearJugador = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaJugadores = new javax.swing.JTable();
        lblBackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        txtNombre.setText("Ingrese Nombre");
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 127, 225, -1));

        btnCrearJugador.setBackground(new java.awt.Color(7, 7, 60));
        btnCrearJugador.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnCrearJugador.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearJugador.setText("Crear Nuevo Jugador");
        btnCrearJugador.setPreferredSize(new java.awt.Dimension(200, 30));
        btnCrearJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 194, 220, 70));

        btnEditar.setBackground(new java.awt.Color(7, 7, 60));
        btnEditar.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setEnabled(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 220, 70));

        lblNombre.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 87, -1, -1));

        tablaJugadores.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        tablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaJugadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaJugadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaJugadores);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 28, 300, 450));

        lblBackGround.setIcon(new javax.swing.ImageIcon("D:\\proyectos_u\\proyecto2\\resource\\BackGroundR510.jpg")); // NOI18N
        lblBackGround.setToolTipText("");
        jPanel1.add(lblBackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 680, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearJugadorActionPerformed
        // TODO add your handling code here:
        String name = txtNombre.getText();
        if (!Utils.checkName(name, this)) {
            return;
        }
        if (!Utils.validatePlayer(name, listaJugadores, this)) {
            return;
        }
        limpiarActualizar();
    }//GEN-LAST:event_btnCrearJugadorActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        windowMain.setFocusMain();
    }//GEN-LAST:event_formWindowClosed

    private void tablaJugadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaJugadoresMouseClicked
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "¿Quiere editar este registro?",
                "Alerta", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);

        if (confirm == 1 || confirm == -1) {
            return;
        }

        int id = tablaJugadores.getSelectedRow();
        txtNombre.setText(listaJugadores.get(id).getNombre());
        indexUpdate = id;
        activeEditRegister();
        //System.out.println(listaJugadores.get(id).getId() + "," + listaJugadores.get(id).getNombre());
    }//GEN-LAST:event_tablaJugadoresMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        String name = txtNombre.getText();
        if (!Utils.checkName(name, this)) {
            return;
        }
        listaJugadores.get(indexUpdate).setNombre(name);
        JOptionPane.showMessageDialog(this, "Nombre Actualizado", "Jugador",
                JOptionPane.INFORMATION_MESSAGE);     
        activeCrearJugador();
        limpiarActualizar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void activeEditRegister() {
        btnCrearJugador.setEnabled(false);
        btnEditar.setEnabled(true);
    }

    private void activeCrearJugador() {
        btnCrearJugador.setEnabled(true);
        btnEditar.setEnabled(false);
    }

    private void limpiarActualizar() {
        txtNombre.setText("Ingrese Nombre");
        txtNombre.requestFocus();
        txtNombre.selectAll();
        cargarListaJugadores();
    }
    
    private void cargarListaJugadores() {
        DefaultTableModel model = (DefaultTableModel) tablaJugadores.getModel();
        model.getDataVector().removeAllElements();
        //model.setRowCount(0);
        for (Player jugador : listaJugadores) {
            model.addRow(new Object[]{jugador.getId(), jugador.getNombre()});
        }
        tablaJugadores.setModel(model);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearJugador;
    private javax.swing.JButton btnEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBackGround;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tablaJugadores;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
